name: Deploy to Production

on:
  push:
    branches:
      - master  # Trigger only on master branch changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}} << 'EOF'
            set -e
            cd ~/app/biznex
            git pull origin master
            docker compose down
            docker compose up -d --build
          EOF